Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\FL_AD\src\server\fedavg.py", line 583, in <module>
    server.run()
  File "C:\Users\User\PycharmProjects\FL_AD\src\server\fedavg.py", line 519, in run
    self.train()
  File "C:\Users\User\PycharmProjects\FL_AD\src\server\fedavg.py", line 240, in train
    self.train_one_round()
  File "C:\Users\User\PycharmProjects\FL_AD\src\server\fedavg.py", line 251, in train_one_round
    (delta, weight,self.client_stats[client_id][self.current_epoch],) = self.trainer.train_ucf(
  File "C:\Users\User\PycharmProjects\FL_AD\src\client\fedavg.py", line 273, in train_ucf
    eval_stats = self.train_and_log_ucf(verbose=verbose)
  File "C:\Users\User\PycharmProjects\FL_AD\src\client\fedavg.py", line 150, in train_and_log_ucf
    before = self.evaluate_ucf()
  File "C:\Users\User\PycharmProjects\FL_AD\src\client\fedavg.py", line 430, in evaluate_ucf
    fpr, tpr, threshold = roc_curve(list(gt[self.testset.indices]), pred)
  File "C:\Users\User\.conda\envs\Federate_learning_project\lib\site-packages\sklearn\metrics\_ranking.py", line 992, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
  File "C:\Users\User\.conda\envs\Federate_learning_project\lib\site-packages\sklearn\metrics\_ranking.py", line 751, in _binary_clf_curve
    check_consistent_length(y_true, y_score, sample_weight)
  File "C:\Users\User\.conda\envs\Federate_learning_project\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [1288, 20608]
wandb: 500 encountered ({"errors":[{"message":"graphql: panic occurred: runtime error: invalid memory address or nil pointer dereference","path":["project"]}],"data":{"project":null}}), retrying request
